# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  win: circleci/windows@5.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs 
jobs:
  build-test-publish:
    executor:
      name: win/default # executor type
      size: medium # can be medium, large, xlarge, 2xlarge
      shell: 'powershell.exe -ExecutionPolicy Bypass'
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps 
    environment:
      NUGET_PACK_VERSION: 0.0.11
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3e:5e:43:bc:19:84:7e:18:76:f6:81:1c:28:57:8a:04"
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Build Package"
          command: dotnet build --configuration Release
      - run:
          name: "Run unit tests"
          command: dotnet test --no-restore --no-build --configuration Release
      - run:
          name: "Create Nuget package"
          command: dotnet pack src\FastACH\FastACH.csproj --no-restore --no-build --include-symbols --configuration Release --output package -p:PackageVersion=$env:NUGET_PACK_VERSION.$env:CIRCLE_BUILD_NUM
      - run:
          name: "Pushing nuget package"
          command: dotnet nuget push package\FastACH.$env:NUGET_PACK_VERSION.$env:CIRCLE_BUILD_NUM.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k $env:NUGET_API_KEY
workflows:
  Build-and-Publish:
    jobs:
      - build-test-publish
